name: Daily Parser

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run events bot script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_USER_ID: ${{ secrets.CHAT_ID }}
        run: python taganrog_events_bot.py

      - name: Commit and push database
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/taganrog_events.db
          git commit -m "auto: update sent events db [skip ci]" || exit 0
          git push
